import {
    Flame,
    Calculator,
    BookText,
    History,
    Newspaper,
    Languages,
    ArrowRightLeft,
    Star,
    Calendar,
    Timer,
    Hourglass,
    Settings,
    Bug,
    User,
    Share2,
    Bot,
    CheckSquare,
    ChevronDown,
    Info,
    Wallet,
    BarChart2,
    Gem,
    Sparkles,
    Wrench,
    Rocket,
    Wand2,
    ChevronUp,
    DollarSign,
    Percent,
} from 'lucide-react';

export const quickAccessItems = [
    { id: 'notes', icon: BookText, label: 'Notes', href: '/notes', requiresAuth: false, color: 'text-indigo-500', bg: 'bg-indigo-500/10' },
    { id: 'loan-calculator', icon: DollarSign, label: 'Loan / EMI', href: '/loan-calculator', requiresAuth: false, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { id: 'discount-calculator', icon: Percent, label: 'Discount', href: '/discount-calculator', requiresAuth: false, color: 'text-rose-500', bg: 'bg-rose-500/10' },
    { id: 'converter', icon: ArrowRightLeft, label: 'Converter', href: '/converter', requiresAuth: false, color: 'text-blue-500', bg: 'bg-blue-500/10' },
    { id: 'calculator', icon: Calculator, label: 'Calculator', href: '/calculator', requiresAuth: false, color: 'text-orange-500', bg: 'bg-orange-500/10' },
    { id: 'date-calculator', icon: Calendar, label: 'Date Calc', href: '/date-calculator', requiresAuth: false, color: 'text-green-500', bg: 'bg-green-500/10' },
    { id: 'todo', icon: CheckSquare, label: 'Todo', href: '/todo', requiresAuth: false, color: 'text-pink-500', bg: 'bg-pink-500/10' },
    { id: 'budget-tracker', icon: Wallet, label: 'Budget', href: '/budget', requiresAuth: false, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { id: 'timer', icon: Timer, label: 'Timer', href: '/timer', requiresAuth: false, color: 'text-red-500', bg: 'bg-red-500/10' },
    { id: 'stopwatch', icon: Hourglass, label: 'Stopwatch', href: '/stopwatch', requiresAuth: false, color: 'text-yellow-500', bg: 'bg-yellow-500/10' },
    { id: 'history', icon: History, label: 'History', href: '/history', requiresAuth: false, color: 'text-purple-500', bg: 'bg-purple-500/10' },
    { id: 'analytics', icon: BarChart2, label: 'Analytics', href: '/analytics', requiresAuth: false, color: 'text-cyan-500', bg: 'bg-cyan-500/10' },
    { id: 'membership', icon: Gem, label: 'Premium', href: '/membership', requiresAuth: false, color: 'text-amber-500', bg: 'bg-amber-500/10' },
    { id: 'about', icon: Info, label: 'About', href: '/about', requiresAuth: false, color: 'text-slate-500', bg: 'bg-slate-500/10' },
];

export const moreAccessItems = [
    { id: 'settings', icon: Settings, label: 'Settings', href: '/settings', requiresAuth: false },
    { id: 'profile', icon: User, label: 'Profile', href: '/profile', requiresAuth: false },
];
